### PR TITLE
Add spring boot samples

### PR DESCRIPTION
**Pull request by branflake2267**

### CODE REVIEW

**Comment by maximmasiutin** [comment]
Thank you very much for the pull request!

Could you please squash all the commits in the pull request into a single commit using the “git rebase -I” command, before we could approve it?

Also, I have a question. The pull request contains verbatim copies of files like “MavenWrapperDownloader.java” from the other sources, e.g., https://github.com/takari/maven-wrapper/blob/master/.mvn/wrapper/MavenWrapperDownloader.java 
The question is: can we avoid copying the files but use other means to get a file rather than duplicating it to our repo?

**Comment by branflake2267** [comment]
Sure I will squash once I'm done updating the readmes and testing against the updates. The PRD said to use the spring boot generator. The Spring boot generator generates the project barebones with this maven wrapper. If I remove it it will no longer match the generated project. Would you like me to remove it and have it no longer match the spring boot generator generated project? @maximmasiutin

**Comment by maximmasiutin** [comment]
@branflake2267 Thank you very much for your explanation! I think that the best way is just to squash and keep the files.

**Comment by branflake2267** [comment]
Ok great. I'm working on testing against the app war updates and will aim to write the readme how tos now.

**Pull request merged**
